setwd("C:/Users/theau/Desktop/Session B Research")
library(readxl)
install.packages("dplyr")
library(dplyr)
QB_Salary <- read_excel("QBsalaray.xlsx")
NFL_Standings <- read_excel("StandingsNFL.xlsx")
QB_Stats <- read_excel("QBstats.xlsx")
QB_Stats_W_Salary <- merge(QB_Stats,QB_Salary,by=c("Year","Player"))
QB_Salary_2019 <- filter(QB_Salary, Year == "2019")
QB_Stats_W_Salary_2018 <- filter(QB_Stats_W_Salary, Year == "2018")
QB_Stats_W_Salary_2017 <- filter(QB_Stats_W_Salary, Year == "2017")
QB_Stats_W_Salary_2016 <- filter(QB_Stats_W_Salary, Year == "2016")
QB_Stats_W_Salary_2015 <- filter(QB_Stats_W_Salary, Year == "2015")
QB_Stats_W_Salary_2014 <- filter(QB_Stats_W_Salary, Year == "2014")
QB_Stats_W_Salary_2013 <- filter(QB_Stats_W_Salary, Year == "2013")
QB_Stats_W_Salary_2012 <- filter(QB_Stats_W_Salary, Year == "2012")
QB_Stats_W_Salary_2011 <- filter(QB_Stats_W_Salary, Year == "2011")
QB_Stats_W_Salary_2010 <- filter(QB_Stats_W_Salary, Year == "2010")
QB_Stats_W_Salary_2009 <- filter(QB_Stats_W_Salary, Year == "2009")
QB_Stats_W_Salary_2008 <- filter(QB_Stats_W_Salary, Year == "2008")
QB_Stats_W_Salary_2007 <- filter(QB_Stats_W_Salary, Year == "2007")
QB_Stats_W_Salary_2006 <- filter(QB_Stats_W_Salary, Year == "2006")
QB_Stats_W_Salary_2005 <- filter(QB_Stats_W_Salary, Year == "2005")
test.fixed <- plm(TD~base)